### ISSUE TITLE
在Android版本4.4的模拟器上启动报错

### ISSUE THREAD

**Issue by singlenoah** [iMeiji/Toutiao#11]
`Process: com.meiji.toutiao, PID: 3910
                                                                 java.lang.NoClassDefFoundError: com.meiji.toutiao.util.SettingUtil$SettingsUtilInstance
                                                                     at com.meiji.toutiao.util.SettingUtil.getInstance(SettingUtil.java:19)
                                                                     at com.meiji.toutiao.InitApp.initTheme(InitApp.java:32)
                                                                     at com.meiji.toutiao.InitApp.onCreate(InitApp.java:24)
                                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4346)
                                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:136)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5019)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                     at dalvik.system.NativeStart.main(Native Method)`

**Comment by iMeiji** [comment]
@singlenoah https://github.com/iMeiji/Toutiao/issues/10
