### ISSUE TITLE
oppor7安装启动崩溃，系统4.4

### ISSUE THREAD

**Issue by xq598359628** [iMeiji/Toutiao#15]
11-14 15:44:16.700 18707-18707/com.meiji.toutiao E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.meiji.toutiao, PID: 18707
                                                                   java.lang.NoClassDefFoundError: com.meiji.toutiao.util.SettingUtil$SettingsUtilInstance
                                                                       at com.meiji.toutiao.util.SettingUtil.getInstance(SettingUtil.java:19)
                                                                       at com.meiji.toutiao.InitApp.initTheme(InitApp.java:32)
                                                                       at com.meiji.toutiao.InitApp.onCreate(InitApp.java:24)
                                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4443)
                                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:143)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1269)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5120)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
                                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by iMeiji** [comment]
@xq598359628 https://github.com/iMeiji/Toutiao/issues/11

**Comment by xq598359628** [comment]
ok了
